[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# API → Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Assets explizit erlauben (WICHTIG!)
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# SPA Catch-All (MUSS zuletzt kommen)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]
